[Data]
adj_filename = data/PEMS04/distance.csv
graph_signal_matrix_filename = data/PEMS04/pems04.npz
num_of_vertices = 307
points_per_hour = 12
num_for_predict = 12
len_input = 12
dataset_name = PEMS04

[Training]
ctx = 0
in_channels = 1
batch_size = 32
model_name = gru
dataset_name = PEMS04
num_of_weeks = 0
num_of_days = 0
num_of_hours = 1
start_epoch = 0
epochs = 100
learning_rate = 0.001
hidden_size = 32
num_layers = 1
dropout = 0.0
loss_function = mse
metric_method = unmask
missing_value = 0.0
